name: eco-innovators-solar
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - ultralytics==8.3.237
      - opencv-python==4.12.0.88
      - numpy
      - pandas
      - requests
      - openpyxl
      - torch
      - torchvision
